In [ ]:
import numpy as np


# 1D Array
a = np.array([1,2,3])

for i in range(len(a)):
    a[i] *= 2
print(type(a))

print(a)

<class 'numpy.ndarray'>
[2 4 6]


In [4]:
# 2D Array

b = np.array([[1,2,3],[4,5,6]])

print(b)
print(type(b))




[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [5]:
# 3D Array

c = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(c)
print(type(c))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


In [ ]:
import pandas as pd

# CREATING OABDAS SERIES FROM A LIST 
s = pd.Series([10, 20, 30], name = "MyNumbers")

print(s)
print(type(s))

0    10
1    20
2    30
Name: MyNumbers, dtype: int64
<class 'pandas.core.series.Series'>


In [8]:
# CREATING A PANDAS DATAFRAME FROM A DICTIONARY

data = {
    'Name':['Alice', 'Bob', 'Charlie'],
    'Age': [25, 45, 20],
    'city': ['New York', 'London', 'Paris'],
    'Salary': [70000, 60000, 90000]
}

df = pd.DataFrame(data)
print(df)

print(type(df))


      Name  Age      city  Salary
0    Alice   25  New York   70000
1      Bob   45    London   60000
2  Charlie   20     Paris   90000
<class 'pandas.core.frame.DataFrame'>
